name: Rust

on:
  push:
    branches: [ master ]
    tags: 'v*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly

    steps:
    - uses: actions/checkout@v2
      
    # build crate
    - name: Build
      run: cargo build --verbose

    # run tests
    - name: Run tests
      run: cargo test --verbose

    # install clippy
    - name: Install clippy
      run: rustup component add clippy

    # lint
    - name: Run clippy
      uses: actions-rs/clippy-check@v1.0.5
      with:
        # Arguments for the cargo command
        args: --verbose
        token: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
          
      # crates.io login  
      - name: Log in to Crates.io
        run: cargo login ${CRATES_IO_TOKEN}
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      
      #crates.io publish
      - name: Publish to Crates.io
        run: cargo publish
